import type { DiaryRecord, EditRequest, ReimbursementRequest, ScheduleRecord, ServiceRegion, SystemSettings } from "./types";

export const initialTechnicians = [
  "ANDRÉ VINICIUS DE OLIVEIRA PEREIRA",
  "Arthur Muller",
  "BEATRIZ DA SILVA RIBEIRO",
  "Bruno Lima Cardoso de Oliveira",
  "CAIO GUERREIRO DE OLIVEIRA",
  "Carolina dos Anjos Cunha",
  "Cleyton Henrique Rodrigues Costa",
  "Daniel da Silva Drumond",
  "Ernani Michel Lima Cardoso de Oliveira",
  "Fabiano de Souza Correaia",
  "Felipe de Araújo Paz",
  "Felipi Silmplício de Oliveira",
  "Fábio de Souza",
  "Horlan da Silva Gonçalves",
  "JOSELITO BORGES BARRETO",
  "JOSILENE MACHADO DE OLIVEIRA",
  "Jairo Marcelo Rodrigues",
  "Joyce de Oliveira Leite",
  "João Paulo dos Santos Filho",
  "LEONARDO DA SILVA BAUER",
  "LETÍCIA MAGALHÃES DE FREITAS",
  "LUIZ FELIPE PEREGRINO AREAS",
  "Lais Maria de Oliveira",
  "Lamaier Rodrigues Ribeiro",
  "Larissa Cristina de Almeida Rodrigues",
  "Leandro da Silva da Costa",
  "Lucas do Nascimento dos Santos",
  "Marcelo Diniz Quadros",
  "Marcos da Silva Damazio",
  "Marcos Vinicius Nunes Almeida",
  "Marcus Vinicius Nogueira Silva",
  "Mary Ellen Santana",
  "Matheus Alves Tavares",
  "Matheus Loyola Araujo",
  "Matheus Souza Ribeiro",
  "Maurício Cabral",
  "Paulo André Vidal Fernandes",
  "Paulo Henrique Barbosa de Souza",
  "Pedro Schenkel Assunção Natário",
  "Rafael de Paula da Silva",
  "Ricardo Elias Antunes de Araújo",
  "Stephanie Barros Oliveira",
  "TESTE",
  "Thiago Pacheco Brito",
  "Thiago Vinícius Matos Mesquita",
  "Victor da Silva Souza",
  "WENDELL KAYDSON DA CONCEIÇÃO PERES",
  "YURI CORDIRO RIBEIRO",
];

export const initialVessels = [
  "AH CAMOGLI",
  "AH GIORGIO P",
  "AH LIGURIA",
  "AH VALLETTA",
  "AH VARAZZE",
  "CBO ALESSANDRA",
  "CBO ALIANÇA",
  "CBO ANA LUISA",
  "CBO ANITA",
  "CBO ANNA GABRIELLA",
  "CBO ARPOADOR",
  "CBO ATLÂNTICO",
  "CBO BIANCA",
  "CBO BOSSA NOVA",
  "CBO CABRÁLIA",
  "CBO CAMPOS",
  "CBO CAROLINA",
  "CBO CHIARA",
  "CBO COPACABANA",
  "CBO ENDEAVOUR",
  "CBO ENERGY",
  "CBO FLAMENGO",
  "CBO GUANABARA",
  "CBO IGUAÇU",
  "CBO IPANEMA",
  "CBO ISABELLA",
  "CBO ITAJAÍ",
  "CBO MANOELLA",
  "CBO MISTRAL",
  "CBO NITERÓI",
  "CBO OCEANA",
  "CBO PACÍFICO",
  "CBO PARINTINS",
  "CBO RENATA",
  "CBO SUPPORTER",
  "CBO TERRA BRASILIS",
  "CBO VALENTINA",
  "CBO VITÓRIA",
  "CBO WAVE",
  "CBO WISER",
  "CBO XAVANTES",
  "DELTA CARDINAL",
  "DELTA COMMANDER",
  "HOSS BRASS RING",
  "SIDDIS SAILOR",
  "SIEM PILOT",
  "SKANDI AMAZONAS",
  "SKANDI CARLA",
  "SKANDI COMMANDER",
  "SKANDI PARATY",
];

export const initialServiceRegions: ServiceRegion[] = [
  { id: "region-macae", name: "Macaé", posts: [] },
  { id: "region-campos", name: "Campos", posts: [] },
  { id: "region-niteroi", name: "Niterói", posts: [] },
  { id: "region-sao-goncalo", name: "São Gonçalo", posts: [] },
];

export const demoRecords: DiaryRecord[] = [
  {
    id: "REG-0710",
    date: "2026-06-11",
    technician: "Leandro da Silva da Costa",
    turns: [
      {
        shift: "Diurno",
        activity: "Area",
        vessels: ["HOSS BRASS RING"],
      },
    ],
    notes: "Acompanhamento de atividade operacional.",
    status: "Registrado",
    createdAt: "2026-06-11T08:12:00",
  },
  {
    id: "REG-0709",
    date: "2026-06-10",
    technician: "Leandro da Silva da Costa",
    turns: [
      {
        shift: "Diurno",
        activity: "Area",
        vessels: ["SKANDI PARATY"],
      },
      {
        shift: "Noturno",
        activity: "ADM",
        vessels: ["SKANDI CARLA"],
      },
    ],
    notes: "Dobra autorizada pela supervisao.",
    status: "Solicitacao enviada",
    createdAt: "2026-06-10T19:35:00",
  },
  {
    id: "REG-0708",
    date: "2026-06-09",
    technician: "Joyce de Oliveira Leite",
    turns: [
      {
        shift: "Noturno",
        activity: "Area",
        vessels: ["SKANDI COMMANDER"],
      },
    ],
    notes: "",
    status: "Registrado",
    createdAt: "2026-06-09T18:02:00",
  },
];

export const demoRequests: EditRequest[] = [
  {
    id: "SOL-0031",
    recordId: "REG-0709",
    technician: "Leandro da Silva da Costa",
    date: "2026-06-10",
    reason: "Embarcacao informada incorretamente no segundo turno.",
    originalRecord: demoRecords[1],
    proposedRecord: {
      ...demoRecords[1],
      turns: [
        demoRecords[1].turns[0],
        { ...demoRecords[1].turns[1], vessels: ["SKANDI COMMANDER"] },
      ],
    },
    status: "Pendente",
    createdAt: "2026-06-11T09:10:00",
  },
];

export const demoScheduleRecords: ScheduleRecord[] = [
  {
    id: "AGD-0001",
    vessel: "SKANDI CARLA",
    scheduledAt: "2026-06-23T07:00",
    osNumber: "OS-CLIENTE-001",
    serviceType: "Operacional",
    status: "Programado",
    region: "Macaé",
    post: "",
    dayTsts: [
      { id: "day-1", name: "Leandro da Silva da Costa", contact: "(21) 99999-9999" },
    ],
    nightTsts: [
      { id: "night-1", name: "Joyce de Oliveira Leite", contact: "(21) 98888-8888" },
    ],
    cboSupports: [
      { id: "cbo-1", name: "Suporte CBO Exemplo", contact: "(21) 97777-7777" },
    ],
    programs: [
      { shift: "Diurno", timeRange: "07:00-19:00HRS" },
      { shift: "Noturno", timeRange: "19:00-07:00HRS" },
    ],
    createdAt: "2026-06-22T12:00:00",
    createdBy: "Coordenador",
    changeHistory: [],
  },
];

export const demoReimbursements: ReimbursementRequest[] = [];

export const defaultSettings: SystemSettings = {
  technicians: initialTechnicians,
  technicianContacts: {},
  cboSupports: [],
  vessels: initialVessels,
  accessAccounts: [
    {
      id: "access-admin",
      role: "admin",
      name: "Administrador",
      username: "admin",
      password: "Muniz@2026",
      active: true,
    },
    {
      id: "access-supervisor",
      role: "supervisor",
      name: "Coordenador",
      username: "Coordenador",
      password: "Martins@2026",
      active: true,
    },
    {
      id: "access-financeiro",
      role: "financeiro",
      name: "Financeiro",
      username: "Financeiro",
      password: "Sea@2026@",
      active: true,
    },
  ],
  allowSelfieDeletion: false,
  serviceRegions: initialServiceRegions,
};
